Clear server after build

diff --git a/docker/production/Dockerfile b/docker/production/Dockerfile
--- a/docker/production/Dockerfile
+++ b/docker/production/Dockerfile
@@ -3,7 +3,6 @@
 FROM node:22-alpine AS base
 RUN apk upgrade --no-cache
 
-# All deps (including devDependencies) — needed for the build step
 FROM base AS deps
 RUN apk add --no-cache libc6-compat
 WORKDIR /app
@@ -15,6 +14,16 @@ RUN \
   else echo "Lockfile not found." && exit 1; \
   fi
 
+FROM base AS prod-deps
+RUN apk add --no-cache libc6-compat
+WORKDIR /app
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile --production; \
+  elif [ -f package-lock.json ]; then npm ci --omit=dev; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --prod; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 FROM base AS builder
 WORKDIR /app
@@ -28,20 +37,22 @@ RUN npm run build
 
 FROM base AS runner
 WORKDIR /app
-
 ENV NODE_ENV=production
-
 RUN addgroup -g 1001 -S nodejs
 RUN adduser -S nextjs -u 1001
-
 COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
 COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
 COPY --from=builder --chown=nextjs:nodejs /app/public ./public
+USER nextjs
+EXPOSE 3000
+CMD ["node", "server.js"]
+
+FROM base AS migrator
+WORKDIR /app
+RUN addgroup -g 1001 -S nodejs
+RUN adduser -S nextjs -u 1001
+COPY --from=prod-deps --chown=nextjs:nodejs /app/node_modules ./node_modules
 COPY --from=builder --chown=nextjs:nodejs /app/app/db/runMigrations.js ./app/db/runMigrations.js
 COPY --from=builder --chown=nextjs:nodejs /app/app/db/migrations ./app/db/migrations
-
 USER nextjs
-
-EXPOSE 3000
-
-CMD ["node", "server.js"]
+CMD ["node", "app/db/runMigrations.js"]
