Fix stage env [skip ci]

diff --git a/docker/staging/Dockerfile b/docker/staging/Dockerfile
--- a/docker/staging/Dockerfile
+++ b/docker/staging/Dockerfile
@@ -1,15 +1,11 @@
 # syntax=docker.io/docker/dockerfile:1
 
-FROM node:20-alpine AS base
+FROM node:22-alpine AS base
+RUN apk upgrade --no-cache
 
-# 1. Install dependencies only when needed
 FROM base AS deps
-# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
 RUN apk add --no-cache libc6-compat
-
 WORKDIR /app
-
-# Install dependencies based on the preferred package manager
 COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
 RUN \
   if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
@@ -18,37 +14,47 @@ RUN \
   else echo "Lockfile not found." && exit 1; \
   fi
 
+FROM base AS prod-deps
+RUN apk add --no-cache libc6-compat
+WORKDIR /app
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile --production; \
+  elif [ -f package-lock.json ]; then npm ci --omit=dev; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --prod; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
-# 2. Rebuild the source code only when needed
 FROM base AS builder
 WORKDIR /app
 COPY --from=deps /app/node_modules ./node_modules
 COPY . .
-# This will do the trick, use the corresponding env file for each environment.
-COPY .env.staging.sample .env.production
+ARG NEXT_PUBLIC_API_URL=http://localhost:3000
+ARG NEXTAUTH_URL=http://localhost:3000
+ARG NEXT_PUBLIC_APP_ENV=staging
+ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
+ENV NEXTAUTH_URL=$NEXTAUTH_URL
+ENV NEXT_PUBLIC_APP_ENV=$NEXT_PUBLIC_APP_ENV
 RUN npm run build
 
-# 3. Production image, copy all the files and run next
 FROM base AS runner
 WORKDIR /app
-
 ENV NODE_ENV=production
-
 RUN addgroup -g 1001 -S nodejs
 RUN adduser -S nextjs -u 1001
-
-COPY --from=builder /app/public ./public
-
-# Automatically leverage output traces to reduce image size
-# https://nextjs.org/docs/advanced-features/output-file-tracing
 COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
 COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
-
-
+COPY --from=builder --chown=nextjs:nodejs /app/public ./public
 USER nextjs
-
 EXPOSE 3000
+CMD ["node", "server.js"]
 
-ENV PORT=3000
-
-CMD HOSTNAME="0.0.0.0" node server.js
+FROM base AS migrator
+WORKDIR /app
+RUN addgroup -g 1001 -S nodejs
+RUN adduser -S nextjs -u 1001
+COPY --from=prod-deps --chown=nextjs:nodejs /app/node_modules ./node_modules
+COPY --from=builder --chown=nextjs:nodejs /app/app/db/runMigrations.js ./app/db/runMigrations.js
+COPY --from=builder --chown=nextjs:nodejs /app/app/db/migrations ./app/db/migrations
+USER nextjs
+CMD ["node", "app/db/runMigrations.js"]
